
version: '3'
services:
  webapp:
    build: ./
    ports:
      - '8080:8080'
    links:
      - mysql
  mysql:
    image: mysql:8.0.17
    restart: always
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - ./mysql/log:/var/log/mysql
      - ./mysql/config:/etc/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files/